server:
  port: 6001
spring:
  application:
    name: auth-gateway
  #  profiles:
  #    active: local
  cloud:
    nacos:
      server-addr: localhost:8848

    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      routes:
        # 权限服务，管理员接口
        - id: auth-permission # 路由的编号
          uri: http://localhost:6002
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/permission/**,/admin-api/permission/*/**
          filters:
            - StripPrefix=2
logging:
  level:
    root: info
