server:
  port: 6003

spring:
  application:
     name: auth-authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/auth-authentication?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

auth:
  # mybatis plus mapper配置
  info:
    mapper-base-package: com.auth.cloud.authentication.mapper
  # swagger配置
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: 1.0.0
    base-package: com.auth.cloud.authentication

# token配置
jwt:
  # 令牌密钥
  secretKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALMcMs+3nbfJvmb6B2avCpYjC/AGKrFJPDGTLnmdi7+LuZpV+YNbijpzQF1hD6X8FuRzLf7vJfZRA8d7tRNBQOWBUmL4bz5L24oS3bU3B7ptbaQZc4iCVfeimpBh2fDoPXBXjBnxHusCHmKSliv+2R6YKihfA9B0C9l3m5yLwgp5AgMBAAECgYEAsRJErZRyyVsa8MVpAbw1dB6r05zVIjYr2zsN7E+z9CdX09wBdDrQml6MmIS3qrphi3LPW0Tku/J2EQYdCy8sztBxfQRYWGMAyWp0F7IuH71hczD0zLbCA049qd4RgzQTiCUAgncx/mSKPP6gjixHklKdRgg9dCMXr5/avVVoT+0CQQDjiPvFE8thCvapK11135q4jNkF1Px1uJohCxoYUO8vTFyeQshT2RXumeinYt8C9azvpoXwBr8wFkH5BoLlEP0/AkEAyYRc0lGwyYSAm7tyGIqbY0428Bs1KTLSYnDuVCR+8seo+RdYuD7eOJjAY2mWKgTyjnEqCRkQXMkEDfgDUIqyRwJBANUk7TSgZlRxwL6YMOTKolVfG62q5xQf6cIqdDdzGZxlHB3k0WQ6Z6Er7BVhOSe8nFOi2rUOnOqe7w4oW1XZpGECQHDvvnmckMCPguhEaBA69hT0i7OK/AMn2WKUOe1sOr1jil53aCByE2aSrRfJ3/+SoEGWSGGq61Gk0qHlgi4MXRcCQAGsaJXFK2sGZ4FDy08MrV9/dPcItGP3GBEHPNVukjYJJAz4Wb53vhwOH2V5S5YxJCfV4z6RyYKXSS3sUDID25A=
  # 令牌有效期（默认2h）
  expiration: 7200
logging:
  level:
    root: info
